# mkdocs.yml
site_name: FURTHRmind python package

theme:
  name: "material"
  logo: "assets/logo.png"
  favicon: "assets/logo.png"

plugins:
  - search
  - mkdocstrings:
      handlers:
          python:
            options:
              docstring_style: numpy
              inherited_members: true


nav:
  - Getting started: index.md
  - References:
    - project.md
    - group.md
    - experiment.md
    - sample.md
    - ResearchItem: researchitem.md
    - file.md
    - field.md
    - FieldData: fielddata.md
    - DataTable: datatable.md
    - column.md
    - ComboBoxEntry: comboboxentry.md
    - unit.md
    - category.md