# mkdocs.yml
site_name: FURTHRmind python wrapper documentation

theme:
  name: "material"

plugins:
  - search
  - mkdocstrings:
      handlers:
          python:
            options:
              docstring_style: numpy

nav:
  - Furthrmind docs: index.md
  - project.md
  - references.md
