# mkdocs.yml
site_name: FURTHRmind python package

theme:
  name: "material"

plugins:
  - search
  - mkdocstrings:
      handlers:
          python:
            options:
              docstring_style: numpy
              inherited_members: true


nav:
  - Getting started: index.md
  - References:
    - experiment.md
    - file.md
